### PR TITLE
Compatible version with asmfmt (save one last issue)

### PR DESCRIPTION
**Pull request by fwessels**
Starting position of the comment is now relaxed to be after either 3, 4, or 5 BYTE sequences and/or followed by an optional back slash.

One remaining issue is that BYTES that are wrapped to the next line (extra indented by asm2plan9s to indicate that this BYTE/these BYTES belong to the previous line) are set back to start at position 4.

This makes it difficult to detect whether it is not any another BYTE sequence (not automatically translated from YASM), so if asmfmt could preserve this it would be great.

### CODE REVIEW

**Comment by klauspost** [comment]
Maybe (since it is automatic, it could use `LONG` and `WORD` to make the byte sequences short, ie.

```
    LONG $0x066ffec5;            // VMOVDQU YMM0, [rsi]
    LONG $0xd073f5c5; BYTE $0x04 // VPSRLQ  YMM1, YMM0, 4   ; X1: high input
```

(Sorry, if my endianness is swapped)

**Comment by fwessels** [comment]
That's a much nicer solution (to get rid of the wrapped lines).

**Comment by klauspost** [comment]
Looking forward to it - feel free to add a comment with a link to your tool to the assembler file in this PR.

**Comment by klauspost** [comment]
LGTM. Have you had the chance to run tests on an AVX2 machine? I don't have it available right at this moment.

**Comment by fwessels** [comment]
I checked the byte sequences so there should be no difference.

But let me double check on an AVX2 server and report back.

BTW I'd be interested in any feedback you might have on the blake2b-simd implementations. Also there is a vague performance issue for Atom where SSE execution seems to be severely handicapped...

**Comment by fwessels** [comment]
All tests passed ok (on AVX2 path)
```
minio@minio3:reedsolomon $ go test
PASS
ok  	github.com/fwessels/reedsolomon	4.229s
```

**Pull request merged**
